services:
  php:
    # environment:
    # PHP_IDE_CONFIG: serverName=factory.local
    # XDEBUG_REMOTE_HOST: ${PHP_XDEBUG_HOST-localhost}
    # XDEBUG_REMOTE_PORT: ${PHP_XDEBUG_PORT-9003}
    # XDEBUG_PROFILER_OUTPUT_DIR: ${PHP_XDEBUG_PROFILER_OUTPUT_DIR}
    # COMPOSER_ALLOW_XDEBUG: '1'
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID-1000}
        GID: ${GID-1000}
    volumes:
      - .:/var/www
      # - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/custom-xdebug.ini

    # networks:
    #   - factory

  nginx:
    image: nginx:alpine-slim
    ports:
      - ${NGINX_HTTP_PORT-80}:80
      - ${NGINX_HTTPS_PORT-443}:443
    environment:
      - "DOMAIN=${DOMAIN}"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # networks:
    #   - factory

  db:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME-database}
      MYSQL_USER: ${DB_USER-user}
      MYSQL_PASSWORD: ${DB_PASSWORD-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD-root}
    ports:
      - ${DB_PORT-3306}:3306
    volumes:
      - db:/var/lib/mysql:rw
    # networks:
    #   - factory

# networks:
#   factory:

volumes:
  db: {}
